# -*- coding: utf-8 -*-
"""Ejercicio6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbllSYCod94YN85sMOnEiHoRQRShqvVX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Cargar el video (reemplaza 'path/to/video.mp4' con la ruta de tu video)
cap = cv2.VideoCapture('video1.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convertir a escala de grises
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Aplicar un filtro de desenfoque
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Detectar bordes
    edges = cv2.Canny(blurred, 50, 150)

    # Encontrar contornos
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Dibujar los contornos en el cuadro original
    cv2.drawContours(frame, contours, -1, (0, 255, 0), 2)

    # Mostrar el cuadro con contornos
    cv2_imshow(frame)

    # Esperar un breve periodo para permitir la visualización
    cv2.waitKey(1)

# Liberar la captura
cap.release()
cv2.destroyAllWindows()