# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTp3KvTdLegXkXkzLk2FU--3YoyJoAa9
"""

import cv2
from google.colab.patches import cv2_imshow

video = cv2.VideoCapture('video2.mp4')

while video.isOpened():
    ret, frame = video.read()
    if not ret:
        break

    resized_frame = cv2.resize(frame, (400, 600))
    edges = cv2.Canny(resized_frame, 100, 200)

    half_width = resized_frame.shape[1] // 2
    left_half = resized_frame[:, :half_width]
    right_half = resized_frame[:, half_width:]

    quarter_height = resized_frame.shape[0] // 2
    top_left = resized_frame[:quarter_height, :half_width]
    top_right = resized_frame[:quarter_height, half_width:]
    bottom_left = resized_frame[quarter_height:, :half_width]
    bottom_right = resized_frame[quarter_height:, half_width:]

    print("Video redimensionado:")
    cv2_imshow(resized_frame)

    print("Detector de bordes:")
    cv2_imshow(edges)

    print("Mitad izquierda:")
    cv2_imshow(left_half)
    print("Mitad derecha:")
    cv2_imshow(right_half)

    print("Cuadrante superior izquierdo:")
    cv2_imshow(top_left)
    print("Cuadrante superior derecho:")
    cv2_imshow(top_right)
    print("Cuadrante inferior izquierdo:")
    cv2_imshow(bottom_left)
    print("Cuadrante inferior derecho:")
    cv2_imshow(bottom_right)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()