# -*- coding: utf-8 -*-
"""Ejercicio5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bChB0--QCgTqexKdT-xFBaktNTPI6md3
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('imagenvision1.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)
edges = cv2.Canny(blurred, 50, 150)
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(img, contours, -1, (0, 255, 0), 2)
cv2_imshow(img)